queue_rules:
  - name: default
    merge_conditions:
      - check-success=buildbot/nix-build
    merge_method: rebase
    batch_size: 5
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|dependencies
    actions:
      queue:
